version: '3.7'
services:
  web-app:
    build: .
    container_name: gatsby_portfolio
    ports:
      - "8000:8000"
      - "7000:7000"
      - "3333:3333"
    volumes:
      - .:/home
    environment:
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
    # depends_on:
    #   - db
    # networks: ['mynetwork']

  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: mysecretpassword
  #     POSTGRES_USER: dipesh
  #     POSTGRES_DB: condo_app
  #   networks: 
  #     - mynetwork

# networks: 
#   mynetwork: